### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by ksonbol** [dbermbach/BenchFoundry#8]
I tried to build the project following the instructions (without test) running:
`mvn clean generate-sources compile 
`
but I got the following 9 build errors:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project BenchFoundry: Compilation failure: Compilation failure: 
[ERROR] /home/karim/BenchFoundry-master/src/generated/de/tuberlin/ise/benchfoundry/rpc/BenchmarkSlaveService.java:[677,7] method does not override or implement a method from a supertype
[ERROR] /home/karim/BenchFoundry-master/src/generated/de/tuberlin/ise/benchfoundry/rpc/BenchmarkSlaveService.java:[702,7] method does not override or implement a method from a supertype
[ERROR] /home/karim/BenchFoundry-master/src/generated/de/tuberlin/ise/benchfoundry/rpc/BenchmarkSlaveService.java:[727,7] method does not override or implement a method from a supertype
[ERROR] /home/karim/BenchFoundry-master/src/generated/de/tuberlin/ise/benchfoundry/rpc/BenchmarkSlaveService.java:[752,7] method does not override or implement a method from a supertype
[ERROR] /home/karim/BenchFoundry-master/src/generated/de/tuberlin/ise/benchfoundry/rpc/BenchmarkSlaveService.java:[778,7] method does not override or implement a method from a supertype
[ERROR] /home/karim/BenchFoundry-master/src/generated/de/tuberlin/ise/benchfoundry/rpc/BenchmarkSlaveService.java:[803,7] method does not override or implement a method from a supertype
[ERROR] /home/karim/BenchFoundry-master/src/generated/de/tuberlin/ise/benchfoundry/rpc/BenchmarkSlaveService.java:[828,7] method does not override or implement a method from a supertype
[ERROR] /home/karim/BenchFoundry-master/src/generated/de/tuberlin/ise/benchfoundry/rpc/BenchmarkSlaveService.java:[853,7] method does not override or implement a method from a supertype
[ERROR] /home/karim/BenchFoundry-master/src/generated/de/tuberlin/ise/benchfoundry/rpc/BenchmarkSlaveService.java:[878,7] method does not override or implement a method from a supertype
```

**Comment by akon-dey** [comment]
Thank you for filing the issue.

I am unable to reproduce the build failure you are observing. To begin with, I would suggest pulling the latest code (git pull) and running the same steps again.

Please capture the full log of the mvn command you run and attach it. Also, please add information about your computer build environment. This will help us get started with solving this issue.

**Comment by ksonbol** [comment]
Thank you for the quick response. 

I have done as you said and here is [the log of the mvn command](https://github.com/dbermbach/BenchFoundry/files/1670523/short_log.txt) and [the longer version using -X](https://github.com/dbermbach/BenchFoundry/files/1670522/log.txt).

I have Ubuntu 16.04, Java 9, and Thrift version 0.11.0.

**Comment by akon-dey** [comment]
It looks like a thrift 11 vs thrift 10 incompatibility. Would you be able to downgrade your Thrift to 0.10.0 and Java to 8 and try. We have not built this with Java 9 and Thrift 0.11.0 before.

I was not able to get Thrift 0.10.0 from the tar to build and install cleanly on Ubuntu 16.04 with either Java 8 or 9.

**Comment by ksonbol** [comment]
Thanks, the build succeeds with Java 8 and Thrift 0.10.0.

**Comment by akon-dey** [comment]
That is good to know. Please let us know if it is important to support Thrift 0.11.0 and Java 9. We will schedule a porting effort sooner.
